name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: zipper
        run: zip latest.zip ${GITHUB_WORKSPACE}

      - name: complete check
        run: |
          echo complete
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta
          release_name: Ver.b1.0
          body: |
            This is beta.
      - name: Upload Release Artifact
        id: upload_artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/latest.zip
          asset_name: latest.zip
          asset_content_type: application/zip
